/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Users {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  is_verified: Generated<boolean | null>;
  password_hash: string | null;
  tg_user_id: Int8 | null;
  tg_username: string;
  two_fa_secret: string | null;
}

export interface VerificationCodes {
  code: string;
  expires_at: Timestamp;
  id: Generated<number>;
  tg_username: string;
}

export interface DB {
  users: Users;
  verification_codes: VerificationCodes;
}
